{ pkgs }: {
  deps = [
    pkgs.firefox
    pkgs.geckodriver
    pkgs.python310Full
    pkgs.python310Packages.pip
    pkgs.libGL
    pkgs.libGLU
    pkgs.xorg.libX11
    pkgs.xorg.libXext
    pkgs.xorg.libXrender
    pkgs.xorg.libXfixes
    pkgs.xorg.libXi
    pkgs.xorg.libXcursor
    pkgs.xorg.libXScrnSaver
    pkgs.xorg.libXcomposite
    pkgs.xorg.libXdamage
    pkgs.xorg.libXrandr
    pkgs.xorg.libXinerama
    pkgs.xorg.libXft
    pkgs.xorg.libXss
    pkgs.xorg.libXxf86vm
    pkgs.freetype
    pkgs.fontconfig
    pkgs.glib
    pkgs.gtk3
    pkgs.cairo
    pkgs.pango
    pkgs.gdk-pixbuf
    pkgs.atk
    pkgs.cups
    pkgs.which
    pkgs.dbus
    pkgs.nss
    pkgs.nsxr
    pkgs.alsa-lib
    pkgs.libdrm
    pkgs.libXScrnSaver
    pkgs.libxkbcommon
    pkgs.wayland
    pkgs.libxshmfence
    pkgs.mesa
    pkgs.libva
    pkgs.libvdpau
    pkgs.libXcomposite
    pkgs.libXcursor
    pkgs.libXdamage
    pkgs.libXext
    pkgs.libXfixes
    pkgs.libXft
    pkgs.libXi
    pkgs.libXinerama
    pkgs.libXrandr
    pkgs.libXrender
    pkgs.libXtst
    pkgs.libXss
    pkgs.libXxf86vm
    pkgs.udev
    pkgs.libnotify
    pkgs.libcap
    pkgs.libv4l
    pkgs.libexif
    pkgs.libuuid
    pkgs.libgudev
    pkgs.pipewire
    pkgs.gnome.adwaita-icon-theme
    pkgs.gnome.gnome-themes-extra
    pkgs.gnome.gsettings-desktop-schemas
    pkgs.gnome.dconf
    pkgs.cups
    pkgs.hicolor-icon-theme
    pkgs.font-cursor-misc
    pkgs.gnome.adwaita-icon-theme
    pkgs.gtk3
    pkgs.shared-mime-info
    pkgs.glib
    pkgs.libnotify
    pkgs.libxkbcommon
    pkgs.xdg-utils
    pkgs.at-spi2-atk
    pkgs.at-spi2-core
    pkgs.cups
    pkgs.dbus
    pkgs.dconf
    pkgs.freetype
    pkgs.gdk-pixbuf
    pkgs.glib
    pkgs.gnome.adwaita-icon-theme
    pkgs.gnome.gnome-themes-extra
    pkgs.gnome.gsettings-desktop-schemas
    pkgs.gtk3
    pkgs.hicolor-icon-theme
    pkgs.libXcomposite
    pkgs.libXcursor
    pkgs.libXdamage
    pkgs.libXext
    pkgs.libXfixes
    pkgs.libXft
    pkgs.libXi
    pkgs.libXinerama
    pkgs.libXrandr
    pkgs.libXrender
    pkgs.libXScrnSaver
    pkgs.libXss
    pkgs.libXtst
    pkgs.libXxf86vm
    pkgs.pango
    pkgs.pipewire
    pkgs.shared-mime-info
    pkgs.wayland
    pkgs.xdg-utils
  ];
}
